[package]
name = "auction_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.30"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
