
services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:5173
  # debug-helper:
  #   image: busybox

  server:
    image: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_HOST: host.docker.internal
    ports:
      - 3001:3001
    env_file: 
      - path: "server/.env"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ah2025
      POSTGRES_DB: pvp
      
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # nginx:
  #   image: nginx:1.20.1
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:80
  #   container_name: reverse-proxy
  #   depends_on:
  #     - client
volumes:
  db: