openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API for managing users with HAL-style hypermedia responses

servers:
  - url: http://localhost:3001/api

paths:
  /login/{user_id}:
    $ref: './paths/login.yaml'
  /users:
    $ref: './paths/users.yaml'
  /users/{user_id}:
    $ref: './paths/user.yaml'
  /users/{user_id}/auctions:
    $ref: './paths/user_auctions.yaml'
  /items:
    $ref: './paths/items.yaml'
  /items/{id}:
    $ref: './paths/item.yaml'
  /auctions:
    $ref: './paths/auctions.yaml'
  /auctions/{auction_id}/bids:
    $ref: './paths/auction_bids.yaml'
  /auctions/{auction_id}/bids/{bid_id}:
    $ref: './paths/bid.yaml'
  /categories:
    $ref: './paths/categories.yaml'
  /categories/{id}:
    $ref: './paths/category.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      $ref: './components/login_schemas.yaml#/LoginRequest'
    LoginResponse:
      $ref: './components/login_schemas.yaml#/LoginResponse'
    User:
      $ref: './components/user_schemas.yaml#/User'
    AddUserRequest:
      $ref: './components/user_schemas.yaml#/AddUserRequest'
    UpdateUserRequest:
      $ref: './components/user_schemas.yaml#/UpdateUserRequest'
    Item:
      $ref: './components/item_schemas.yaml#/Item'
    AddItemRequest:
      $ref: './components/item_schemas.yaml#/AddItemRequest'
    UpdateItemRequest:
      $ref: './components/item_schemas.yaml#/UpdateItemRequest'
    Auction:
      $ref: './components/auction_schemas.yaml#/Auction'
    AddAuctionRequest:
      $ref: './components/auction_schemas.yaml#/AddAuctionRequest'
    Bid:
      $ref: './components/bid_schemas.yaml#/Bid'
    Category:
      $ref: './components/category_schemas.yaml#/Category'
    AddCategoryRequest:
      $ref: './components/category_schemas.yaml#/AddCategoryRequest'
  responses:
    BadRequest:
      $ref: './components/responses.yaml#/BadRequest'
    NotFound:
      $ref: './components/responses.yaml#/NotFound'
    InternalServerError:
      $ref: './components/responses.yaml#/InternalServerError'